FROM node:lts-alpine AS builder
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:lts-alpine AS runner
WORKDIR /app
ENV HOSTNAME="0.0.0.0"

COPY --from=builder /app .

EXPOSE 3000
CMD ["npm", "run", "dev"]