FROM node:lts-alpine AS builder
WORKDIR /app
ARG NEXT_PUBLIC_API_ENTRYPOINT
ARG API_SERVER_ENTRYPOINT
ENV NEXT_PUBLIC_API_ENTRYPOINT=${NEXT_PUBLIC_API_ENTRYPOINT}
ENV API_SERVER_ENTRYPOINT=${API_SERVER_ENTRYPOINT}
COPY ./package.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

FROM node:lts-alpine AS runner
WORKDIR /app
ENV HOSTNAME="0.0.0.0"

COPY --from=builder /app .

EXPOSE 3000
CMD ["npm", "start"]