services:
  caddy:
    image: caddy:2-alpine
    profiles: ["prod"]
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mern_net
  mernfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"   
    depends_on:
      - nodebackend
    networks:
      - mern_net
  nodebackend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"   
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mern_net
  db:
    volumes:
      - mern_db:/data/db
    image: mongo:7.0.30
    networks: 
      - mern_net
    ports:
      - "127.0.0.1:27017:27017" # Bind ONLY to the local loopback interface
    healthcheck: # Ensures backend doesn't try to connect before DB is initialized
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
   mern_db:
   caddy_data:
   caddy_config:
networks:
    mern_net:
        driver: bridge