FROM node:latest
WORKDIR /app
COPY ./package.json ./package.json
COPY ./server.js ./server.js
COPY ./routes ./routes  
COPY ./models ./models
# Put other js files here

RUN npm install 
EXPOSE 5000
CMD ["node", "server.js"]