name: Deploy to DigitalOcean

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Deploy with SSH
            uses: appleboy/ssh-action@v1.2.5
            with:
                host: ${{secrets.HOST}}
                username: ${{secrets.USERNAME}}
                key: ${{secrets.SSH_KEY}}
                envs: GITHUB_REF_NAME
                script: |
                    cd /root/MERN_Project
                    git fetch origin
                    git checkout -B $GITHUB_REF_NAME origin/$GITHUB_REF_NAME
                    git pull origin $GITHUB_REF_NAME
                    docker compose down
                    docker compose up -d --build


